"""Migración inicial

Revision ID: 5469883b6eb7
Revises: 
Create Date: 2025-07-14 22:37:25.754243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5469883b6eb7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('componentes',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Componente', sa.String(), nullable=True),
    sa.Column('Nombre', sa.String(), nullable=False),
    sa.Column('Descripcion', sa.String(), nullable=True),
    sa.Column('Tipo', sa.String(), nullable=True),
    sa.Column('Foto', sa.String(), nullable=True),
    sa.Column('Marca', sa.String(), nullable=True),
    sa.Column('Modelo', sa.String(), nullable=True),
    sa.Column('Precio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('ID_Componente')
    )
    op.create_table('maquinas',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Codigo', sa.String(), nullable=False),
    sa.Column('Nombre', sa.String(), nullable=False),
    sa.Column('Marca', sa.String(), nullable=True),
    sa.Column('Modelo', sa.String(), nullable=True),
    sa.Column('Año', sa.Integer(), nullable=True),
    sa.Column('Estado', sa.String(), nullable=True),
    sa.Column('Observaciones', sa.String(), nullable=True),
    sa.Column('Foto', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Codigo')
    )
    op.create_table('proveedores',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Nombre', sa.String(), nullable=False),
    sa.Column('Localidad', sa.String(), nullable=True),
    sa.Column('Contacto', sa.String(), nullable=True),
    sa.Column('Telefono', sa.String(), nullable=True),
    sa.Column('Email', sa.String(), nullable=True),
    sa.Column('Rubro', sa.String(), nullable=True),
    sa.Column('Direccion', sa.String(), nullable=True),
    sa.Column('Observaciones', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('componentes_proveedores',
    sa.Column('ID_Proveedor', sa.Integer(), nullable=False),
    sa.Column('ID_Componente', sa.Integer(), nullable=False),
    sa.Column('Cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Componente'], ['componentes.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_Proveedor'], ['proveedores.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_Proveedor', 'ID_Componente')
    )
    op.create_table('compras',
    sa.Column('ID_Compra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Proveedor', sa.Integer(), nullable=True),
    sa.Column('ID_Componente', sa.Integer(), nullable=True),
    sa.Column('Cantidad', sa.Integer(), nullable=True),
    sa.Column('Precio_Unitario', sa.Float(), nullable=True),
    sa.Column('Observacion', sa.String(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ID_Componente'], ['componentes.ID'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ID_Proveedor'], ['proveedores.ID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID_Compra')
    )
    op.create_table('frecuencias',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Maquina', sa.Integer(), nullable=True),
    sa.Column('ID_Componente', sa.Integer(), nullable=True),
    sa.Column('Frecuencia', sa.Integer(), nullable=True),
    sa.Column('Unidad_tiempo', sa.String(), nullable=True),
    sa.Column('Criterio_adicional', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ID_Componente'], ['componentes.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_Maquina'], ['maquinas.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('maquinas_componentes',
    sa.Column('ID_Maquina', sa.Integer(), nullable=False),
    sa.Column('ID_Componente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ID_Componente'], ['componentes.ID'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ID_Maquina'], ['maquinas.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID_Maquina', 'ID_Componente')
    )
    op.create_table('pagos_proveedores',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Proveedor', sa.Integer(), nullable=True),
    sa.Column('Monto', sa.Float(), nullable=True),
    sa.Column('Metodo', sa.String(), nullable=True),
    sa.Column('Observacion', sa.String(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ID_Proveedor'], ['proveedores.ID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('stock',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ID_Componente', sa.Integer(), nullable=True),
    sa.Column('Cantidad', sa.Integer(), nullable=True),
    sa.Column('Tipo', sa.String(), nullable=True),
    sa.Column('Observacion', sa.String(), nullable=True),
    sa.Column('Fecha', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['ID_Componente'], ['componentes.ID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stock')
    op.drop_table('pagos_proveedores')
    op.drop_table('maquinas_componentes')
    op.drop_table('frecuencias')
    op.drop_table('compras')
    op.drop_table('componentes_proveedores')
    op.drop_table('proveedores')
    op.drop_table('maquinas')
    op.drop_table('componentes')
    # ### end Alembic commands ###
