version: '3.8'

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sistema_gestion_agricola
      POSTGRES_USER: elorza
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  # Backend Flask
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://elorza:password123@postgres:5432/sistema_gestion_agricola
      - USE_REACT=false
      - FRONTEND_MODE=html
    volumes:
      - ./sistema_gestion_agricola:/app
      - ./frontend/dist:/app/static/dist
    depends_on:
      - postgres
    networks:
      - app-network

  # Frontend Vite (desarrollo)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge